### ISSUE TITLE
Py 3.9 issue

### ISSUE THREAD

**Issue by jcnovoa** [erenyasarkurt/OpenAI-AWS-Lambda-Layer#1]
"errorMessage": "Unable to import module 'lambda_function': \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.9 from \"/var/lang/bin/python3.9\"\n  * The NumPy version is: \"1.23.5\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: No module named 'numpy.core._multiarray_umath'\n",
  "errorType": "Runtime.ImportModuleError",

**Comment by edwardxwu** [comment]
I ran into the same issue with my home-built layer as well. But I could work around it by adding AWS's own pandas layer on top of the openai layer.

**Comment by erenyasarkurt** [comment]
It has been fixed and merged to the main branch.

**Comment by jcnovoa** [comment]
Thank you, I tested and it worked, much appreciated.

**Comment by erenyasarkurt** [comment]
You're welcome @jcnovoa. Thanks for reporting the issue.

**Comment by yingdi11** [comment]
I am still seeing this issue. It works when I use Architecture: x86_64 but failed when I use arm64
![Screenshot 2022-12-28 181205](https://user-images.githubusercontent.com/12092549/209890935-5f4e6cce-4ebc-44ce-bc97-a80df7a563b4.png)

**Comment by erenyasarkurt** [comment]
Yes, the layer is currently only compatible with the x86_64 architecture. I'm planning to add arm64.
